#Makefile for 1-Parallel Exercise1 INF236-spring19 
CCFLAGS = -O3 -std=c++11 #-fopenmp 
CC = mpicxx

tprop : Cellular1D-Parallel.cpp 
	$(CC) $(CCFLAGS) Cellular1D-Parallel.cpp -o Cellular1D-Parallel

