#Makefile for 2-Parallel Exercise1 INF236-spring19 
CCFLAGS = -g -std=c++11 #-fopenmp -O3
CC = mpicxx

tprop : Cellular2D-Parallel.cpp 
	$(CC) $(CCFLAGS) Cellular2D-Parallel.cpp -o Cellular2D-Parallel

