#Makefile for 2-Sequential Exercise1 INF236-spring19 
CCFLAGS = -g -std=c++11 #-fopenmp -O3
CC = c++

tprop : Cellular2D-Sequential.cpp 
	$(CC) $(CCFLAGS) Cellular2D-Sequential.cpp -o Cellular2D-Sequential

