#Makefile for 1-Sequential Exercise1 INF236-spring19 
CCFLAGS = -O3 -std=c++11 #-fopenmp 
CC = c++

tprop : Cellular1D-Sequential.cpp 
	$(CC) $(CCFLAGS) Cellular1D-Sequential.cpp -o Cellular1D-Sequential

