#Makefile for 1-Sequential Exercise1 INF236-spring19 
CCFLAGS = -O3 -std=c++11 #-fopenmp 
CC = c++

all : Branching-Sequential.cpp 
	$(CC) $(CCFLAGS) Branching-Sequential.cpp -o Branching-Sequential

